#!/bin/bash
#update file hosts with blacklist

set -u 
#set -e

TMPDIR="$(mktemp -d)"
#SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SCRIPT_DIR=/home/andrea/projects/dnsmasq_blocklist_optimizer
trap 'rm -rf -- "$TMPDIR"' EXIT

pushd $TMPDIR
# download list of lists to download
curl https://v.firebog.net/hosts/lists.php?type=tick -o urls.txt
#  gets actual files
wget -q -i urls.txt & 
# in the meantime download other lists
wget -q https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts &
wget -q https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt &
wget -q https://dbl.oisd.nl/ &
wait
# we can dispose tmp list of urls
rm urls.txt
# parse and generate blocklist, with filtering and deduplication
$SCRIPT_DIR/gen_dns_blocklist.py * > /etc/blocked.hosts
systemctl restart dnsmasq
popd

